# This version hides the underlying postgres database on a backend network
# different from the frontend network on which nginx interfaces mlflow.
# And mlflow is hidden behind nginx, allowing user auth to be implemented.
#
# Have the following environment vars set in shell before running docker-compose
# (suggested values here but can use whatever desired):
# export DB_NAME=mlflowdb
# export DB_USER=postgres

services:
    db:
        restart: always
        image: postgres:latest
        container_name: mlflow_db
        expose:
            - ${DB_PORT}
        networks:
            - backend
        environment:
            - MUID=$UID
            - MGID=$GID
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PW}
        volumes:
            - db_datapg:/var/lib/postgresql/data
    mlflow_sftp:
        restart: always
        image: atmoz/sftp:debian
        container_name: mlflow_sftp
        working_dir: "/home/mlflow"
        volumes:
            - ./mlflow/artifacts:/home/mlflow/artifacts
            - ./keys/ssh_sftp_key.pub:/home/mlflow/.ssh/keys/ssh_sftp_key.pub:ro
#        command: ${SFTP_USER}:${SFTP_PW}:::artifacts
        command: mlflow::1001 labs:pass:1002
        ports:
          - "2222:22"
        networks:
            - frontend
            - backend
    mlflowserver:
        restart: always
        build: ./mlflow
        image: mlflowserver
        container_name: mlflowserver
        working_dir: "/mlflowserver"
        networks:
            - frontend
            - backend
        environment:
            - BACKEND=postgresql://${DB_USER}:${DB_PW}@db:${DB_PORT}/${DB_NAME}
            - ARTIFACTS=sftp://${SFTP_USER}:${SFTP_PW}@localhost:2222/mlflow/artifacts
        volumes:
            - ./artifacts:/mlflowserver
            - ./keys/ssh_sftp_key:/root/.ssh/keys/ssh_sftp_key:ro
            - ./keys/config:/root/.ssh/config:ro
         #--default-artifact-root $${ARTIFACTS} && ssh-keyscan -H mlflow_sftp >> ~/.ssh/known_hosts
        command:
            - sh    # (sh allows for var substitution of BACKEND and ARTIFACTS)
            - -c
            - mlflow server
                --port ${MLFLOW_PORT}
                --host 0.0.0.0
                --backend-store-uri $${BACKEND}
                --default-artifact-root $${ARTIFACTS}
#        command: >
#            bash -c "sleep 3
#            && mlflow server
#                --port 5001
#                --host 0.0.0.0
#                --backend-store-uri postgresql://${DB_USER}:${DB_PW}@db:${DB_PORT}/${DB_NAME}
#                --file-store /mlflowserver/mlruns"
        depends_on:
            - db
            - mlflow_sftp

    nginx:
        restart: always
        build: ./nginx
        image: mlflow_nginx
        container_name: mlflow_nginx
        ports:
            - "80:80"
        networks:
            - frontend
        depends_on:
            - mlflowserver

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge

volumes:
    db_datapg:
    mlrun_data:
